name: epicsapps

# conda env create -f environment.yml
# conda activate epicsapps
# run_epicsapps stripchart
# https://pyepics.github.io/epicsapps/stripchart.html

# conda env remove -n epicsapps

channels:
  - defaults
  - conda-forge

dependencies:
  - python >=3.7
  - lmfit>=0.9.13
  - matplotlib>=3.0
  - numpy>=1.15
  - pillow
  - pip
  - pyepics>=3.4.0
  - pyfai
  - pyshortcuts>=1.6
  - requests
  - six>1.11
  - sqlalchemy>=0.9
  - wxmplot>=0.9.38
  - wxpython>=4.0.3
  - wxutils>=0.2.3
  - xraydb
  - yaml

  - pip:
    - versioneer
    - git+https://github.com/BCDA-APS/epicsapps.git#egg=epicsapps
